name: Smoke test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    uses: atlas-field-systems/.github/.github/workflows/node-ci.yml@53648b1be3fe9e1cb280856958ae89eaab6b79c2
