name: Smoke test

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    uses: atlas-field-systems/.github/.github/workflows/node-ci.yml@091cb3e94fbd14195c01ba5915f954d83cc924a6
